### ISSUE TITLE
Question: Get inlined files as result

### ISSUE THREAD

**Issue by aletorrado** [Polymer/polymer-bundler#351]
Hi, I'm trying to replicate the `polymer build` cli feature in gulp, as in the bundled folder. I need to get the list of files bundled into the shell app to avoid duplicating them in the fragments files.

Is this possible now?

Thank you.

**Comment by usergenic** [comment]
@danbeam put https://github.com/Polymer/vulcanize/pull/401 as possible solution.  It doesn't correctly deal with the results of invocations with `--exclude` however, which is going to be problematic for sharding scenarios, which also need this feature, so proposal will be to explicitly accumulate collection of inlined file names during production for this purpose.

The coming-soon major semver release of vulcanize should provide this feature in a more integrated way because of the notion of manifests that we are working with during the pre-inlining phase.

**Comment by usergenic** [comment]
This was provided for by vulcanize's `--out-request-list` option and the `--manifest-out` option in polymer-bundler.

```
$ echo 'alert(1)' > blah.js
$ echo '<script src="blah.js"></script>' > blah.html
```

vulcanize:
```
$ vulcanize blah.html --inline-script --out-request-list filelist
<html><head><meta charset="UTF-8"><script>alert(1)
</script>
</head><body></body></html>
$ cat filelist
/Users/brendanb/src/scratch/vulctest/blah.html
/Users/brendanb/src/scratch/vulctest/blah.js
```

polymer-bundler:
```
$ polymer-bundler --manifest-out manifest.json blah.html --inline-scripts
<script>alert(1)
</script>
$ cat manifest.json
{"blah.html":["blah.html","blah.js"]}
```
