### ISSUE TITLE
Excludes option doesn't work

### ISSUE THREAD

**Issue by jaichandra** [Polymer/polymer-bundler#358]
I have the imports defined as below:

`<link rel="import" href="../../../polymer/polymer.html">`

I use `Polymer-cli` and the path is relative to my project folders. Polymer doesn't exist in the above path, but polymer-cli maps the path correctly to bower_components as per its documentation when I use `polymer serve`.

However, vulcanize fails even if I have the `excludes.imports` defined.

I am using gulp-vulcanize, but I think this is correct.

```
vulcanize({
    inlineScripts: true,
    inlineCss: true,
    excludes: {
        imports: [
            "polymer.html"
        ]
    },
    "strip-excludes": false
})
```

I would like to ignore these imports from vulcanize (but leave the `<link rel="import"...>` lines so that they are imported once, only if required.

**Comment by jaichandra** [comment]
Below config also didn't work.
```
vulcanize({
    inlineScripts: true,
    inlineCss: true,
    excludes: [
        "polymer.html"
    ],
    stripExcludes: false
})
```

**Comment by kristfal** [comment]
This is working, but you probably have issues with your paths. Try using `path.resolve`, and ensure that you exclude the correct `polymer.html`:

```
.pipe($.vulcanize({
      dest: 'dist/elements',
      strip: true,
      inlineCss: true,
      inlineScripts: true,
      excludes: [path.resolve('dist/bower_components/polymer/polymer.html')]
    }))
```

For instance, if you have `polymer.html` in `bower_components` of your root folder and polymer is still included, check if your import is actually happening via `dist/bower_components` (as in my case). 

`path.resolve` will give you error messages if it can't resolve the path, so that should help you debug your particular case.

**Comment by jaichandra** [comment]
My import is happening using relative path `../../../polymer/polymer.html`, and when I run vulcanize (using `path.resolve`), I get path errors like below:
`ERROR finding /Users/<user>/Documents/projects/polymer/polymer.html`

Here's my folder structure:
-| -projects (parent directory)
---| polymer_project_folder
-----| bower_components
-----| src
-------| element
---------| element.html (`../../../polymer/polymer.html`)

This works fine running `polymer serve`, but not with vulcanize. `../../../polymer/polymer.html` is getting resolved to my parent directory (`projects` here).

**Comment by usergenic** [comment]
Bundler's `excludes` option now supports specific js and css scripts as well as folders.  Please note that the exclude values need to be relative paths from the root of the analyzed project, so 'polymer.html' should probably be 'bower_components/polymer/polymer.html'

Try rewriting your gulp file with polymer-build and polymer-bundler instead of gulp-vulcanize and should work fine.
