### ISSUE TITLE
1.x vulcanize: transitive --exclude has issues(?)

### ISSUE THREAD

**Issue by danbeam** [Polymer/polymer-bundler#440]
In chrome, we have files that don't reside on disk.  We exclude those files from vulcanize.

For some reason, when excluding a file with an excluded URL in it, stuff blows up.

```shell
$ echo '<script src="strings.js"></script>' | tee bar.html | tee foo.html
$ vulcanize --exclude strings.js --exclude bar.html foo.html
ERROR finding strings.js
(node:4169) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'strings.js'
<html><head><meta charset="UTF-8"><script src="strings.js"></script>
</head><body></body></html>
```

@justinfagnani @usergenic @tjsavage

**Comment by danbeam** [comment]
as discovered by @freshp86

**Comment by freshp86** [comment]
Note that
```
vulcanize --exclude strings.js foo.html
```

works fine. It does not try to fetch the non-existing strings.js. I think the problem lies at https://github.com/Polymer/polymer-bundler/blob/1.x/lib/vulcan.js#L435, where it tries to find all transitive deps of an exclude, without taking into account other excludes (they are not passed to the analyzer).

**Comment by usergenic** [comment]
This has been released in latest npm package vulcanize 1.15.4

**Comment by danbeam** [comment]
woohoo!  thanks @usergenic and @justinfagnani for taking a look at both our patches!

**Comment by danbeam** [comment]
for future, reference, btw: we're happy to write tests if it makes your lives easier.
