### ISSUE TITLE
Inlines are in the wrong order if a fragment is also eagerly imported.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-bundler#517]
This is from a customer issue we debugged at I/O.

The scenario is app.html imports home.html with imports utils.html. home.html is specified as a fragment though, and then gets inlined before utils.html, causing runtime errors. Removing home.html as a fragment fixes the issue.

**Comment by usergenic** [comment]
Repro:
```html
<!-- shared-thing.html -->
<script>'I should be inlined before fragment-a';</script>
```
```html
<!-- fragment-a.html -->
<link rel='import' href='shared-thing.html'>
```
```html
<!-- shell.html -->
<link rel='import' href='fragment-a.html'>
```
Bundled:
```html
<!-- shell.html -->
<link rel='import' href='fragment-a.html'>
<script>'I should be inlined before fragment-a';</script>
```

This occurs because shared things are injected into the shell.  Currently, they are blithely appended to the shell body, but this is problematic in the case where a non-inlined eager-import is part of the shell and depends on the thing being injected (in this case `fragment-a.html` depends on `shared-thing.html` coming before it.

A solution is to prepend inlined unvisited dependencies of the eagerly imported bundles before their links.
