### ISSUE TITLE
Absolute path - Unable to get document error

### ISSUE THREAD

**Issue by govis** [Polymer/polymer-bundler#521]
Using absolute path (polymer-bundler D:\\Folder\...\file.html) yields the following error (on Windows 10):

Unable to get document D:\\Folder\...\file.html: Document not found: D:\\Folder\...\file.html

Adding -p spits out "UNKNOWN_OPTION: Unknown option: -p"

**Comment by VandeurenGlenn** [comment]
@usergenic 
I'm having the same issue, created an urlLoader and the url passed in canload & load are missing the drive letter (c:)

```js
class FakeFsUrlLoader {
  constructor(files) {
    this.files = files;
  }

  canLoad(url) {
    // url = Workspace/... while D:\Workspace is expected
  }

  load(url) {
    ...
   }
}
```

**Comment by usergenic** [comment]
Does your document itself contain urls in Windows path form or is this only an issue when running the bin/polymer-bundler.js CLI tool with the in-html argument equal to an absolute Windows path?

If the latter, I recommend the following adjustment to your invocation: (using `--in-html` only for clarity)

`polymer-bundler --root D:\Whatever\Your\Folder\Is --in-html file.html`

Please note that `vulcanize -p` analog is `polymer-bundler -r` or `polymer-bundler --root`.  The change was in part because vulcanize did more with `-p` than just set the package root for vulcanization (it attempted to adjust all paths to abspaths etc)

Please let me know if that doesn't work. @VandeurenGlenn and @govis

**Comment by usergenic** [comment]
Also wrt to the FakeFsUrlLoader, the `load` and `canLoad` should never be called with `D:\Whatever\file.html` because `D:\Whatever\file.html` is not a valid **url**.

**Comment by usergenic** [comment]
Closing this bug.  Please respond if you continue to have issues even with the `-r|--root` option.

**Comment by VandeurenGlenn** [comment]
@usergenic Ok, that I didn't know, thanks !
