### ISSUE TITLE
--exclude flag behavior different than Vulcanize

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-bundler#556]
This is a difference I noticed while trying to migrate from Vulcanize to polymer-bundler in Chromium. It's not necessarily a bug, but I am listing it here for completeness, and at the same time I am examining whether I can accommodate this difference by changing the way polymer-bundler is called.

The behavior of `--exclude` is different between polymer-bundler and vulcanize

In vulcanize `--exclude foo.css` would prevent `<link rel="stylesheet" href="foo/foo.css">` from being inlined.

In polymer-bundler `--exclude foo.css` does not prevent it. It only prevents a `link` tag from being inlined if it matches exactly, for example `<link rel="stylesheet" href="foo.css">`

In Chromium currently there are a few files where we exclude them using the filename only, not the complete path, see [here](https://cs.chromium.org/chromium/src/chrome/browser/resources/vulcanize_gn.py?l=46-52).

cc @usergenic

**Comment by freshp86** [comment]
/cc @danbeam
Actually the difference is deeper than I initially reported above, and more serious. Will try to explain below.

In Vulcanize, when an HTML file is excluded, all of its transitive dependencies are also excluded. In polymer-bundler this is not the case. Simplified example below:

parent.html contents
```html
<link rel="import" href="child1.html">
<link rel="import" href="child2.html">
<div>hello from parent.html</div>
```

child1.html contents
```html
<link rel="import" href="child2.html">
<div>hello from child1.html</div>
```

child2.html contents
```html
<div>hello from child2.html</div>
```

Using vulcanize as follows
```
node node_modules/vulcanize/bin/vulcanize --exclude child1.html parent.html
```
the output looks as follows
```html
<html><head><meta charset="UTF-8"></head><body><div hidden="" by-vulcanize=""><link rel="import" href="child1.html"></div><div>hello from parent.html</div>
</body></html>
```
Notice that `child2.html` **has not been inlined**, even though it was a direct dependency of `parent.html`. In fact the top-level `child2.html` import has been removed.

Using polymer-bundler as follows
```
node node_modules/polymer-bundler/lib/bin/polymer-bundler.js --exclude child1.html --in-html parent.html
```
the output looks as follows
```html
<div hidden="" by-polymer-bundler=""><link rel="import" href="child1.html"><div>hello from child2.html</div>
</div><div>hello from parent.html</div>
```
Notice how `child2.html` **has been inlined**, even though it is a dependency of the excluded `child1.html`. The side effect of this in Chromium is that even though [we are excluding](https://cs.chromium.org/chromium/src/chrome/browser/resources/vulcanize_gn.py?l=45) our [ polymer.html file](https://cs.chromium.org/chromium/src/ui/webui/resources/html/polymer.html), all of polymer is being inlined in the final output.

I understand that we could explicitly exclude all of polymer (polymer-mini.html, polymer-micro.html etc), but this sounds brittle. Any thoughts/suggestions? Is the difference in `--exclude` flag semantics intentional?

**Comment by freshp86** [comment]
The issue reported above seems to be related to https://github.com/Polymer/polymer-bundler/issues/286 (although that one seems older and probably refers to Vulcanize).

**Comment by danbeam** [comment]
did you try both stripping excludes and excluding like mentioned here? https://github.com/Polymer/polymer-bundler/issues/286#issuecomment-165253290

**Comment by freshp86** [comment]
`--strip-exclude` does not exist for polymer-bundler, but even so it's not what we need (which is why we don't use it in our Vulcanize flow anyway).

**Comment by usergenic** [comment]
> In vulcanize `--exclude foo.css` would prevent `<link rel="stylesheet" href="foo/foo.css">` from being inlined.
>
>In polymer-bundler `--exclude foo.css` does not prevent it. It only prevents a link tag from being inlined if it matches exactly, for example `<link rel="stylesheet" href="foo.css">`

FWIW, if this is a breaking change with vulcanize, it is intentional, for the obvious advantages offered by the dis-ambiguity of requiring the full-path (note that it's not exact string matches of urls blocked, but rather exact matches of their full path from the package root, which is either the current working directory or the provided `-r|--root` option to polymer-bundler.

> I understand that we could explicitly exclude all of polymer (polymer-mini.html, polymer-micro.html etc), but this sounds brittle. Any thoughts/suggestions? Is the difference in --exclude flag semantics intentional?

Right now, the html import exclusion in the invocation `polymer-bundler --exclude child1.html --in-html parent.html` operates naively and without due consideration of the transitive dependencies etc.  There is a question of ordering here too which is important to note.  If `parent.html` was written as the following, then as a developer I would probably expect child2.html to be inlined or be preserved, since its dependency wasn't satisfied.

```html
<link rel="import" href="child2.html">
<div>something that depends on child2.html being loaded here</div>
<link rel="import" href="child1.html">
<div>hello from parent.html</div>
```

However, to understand the current behavior of `--exclude` in comparison to vulcanize's behavior we should understand that the primary difference between polymer-bundler and vulcanize is that polymer-bundler actually has a model for multiple bundles/shards, whereas vulcanize does not.

Since vulcanize did not have that model, it simply performed its exclude by walking the DOM and import graph and removing links to already visited dependencies (hence removal of the import link to child2.html in the bundled parent.html) because vulcanize knew when it got there that whatever child1.html looks like, it is resolving that dependency and it is redundant.

Now because polymer-bundler actually is designed to know and care about the entire bundling strategy for the project, it can know whether child2.html is being packaged into child1.html directly, put into a different shared bundle or is in a shell.html or what-have-you.  This is important, because it means that polymer-bundler might now simply be able to do what you need in one invocation.

Bundler uses the term "entrypoint" (aka each provided `in-html` value to the bundler CLI is an entrypoint) to refer to nodes that must preserve their independence as they are unique entrypoints into the dependency graph for the project.  Note: if you have more than one entrypoint, the resulting bundling operation will be at least as many files, instead of a single file, so an '--out-dir` option must be given to the command, since it doesn't make much sense to stream a concatenated result to stdout.

So, consider the example from earlier with parent.html, child1.html and child2.html:
```bash
$ OUTDIR=bundled
$ mkdir -p $OUTDIR && rm -rf OUTDIR/* # clean the output folder
$ node node_modules/polymer-bundler/lib/bin/polymer-bundler.js \
  --exclude child1.html \
  --in-html parent.html \
  --in-html child1.html \
  --out-dir $OUTDIR
```

Now in that folder you'd probably have:
```
./bundled/parent.html
./bundled/child1.html
./bundled/shared_bundle_1.html
```

That shared_bundle_1.html is a result of bundler identifying that parent.html and child1.html both import child2.html and creating a bundle for their shared dependencies.  If they both imported child3.html that would be in there too.

In your real-world case, you're probably interested in treating the polymer library as an entrypoint to preserve it, so the following invocation (assuming the redirects for your `chrome://` prefixes are given as well) might serve your needs?

```bash
$ node node_modules/polymer-bundler/lib/bin/polymer-bundler.js \
  --in-html chrome://resources/html/polymer.html
  --in-html chrome://whatever/main/page.html
  --out-dir bundled/
```

I'll look more into options for eliminating child2.html from parent.html.  A strip-excludes option would be necessary unless the child1.html bundle is defined as containing the child2.html file, in which case bundler would strip the link to child2.html (technically it would convert it to a link to child1.html and remove as duplicate after seeing that child1.html was visited right above it.)

We can also chat to see if using polymer-bundler's multiple-bundle model would be a good solution for you.

**Comment by usergenic** [comment]
I think it would go *something like this* for chromium (dunno yer paths exactly)
```bash
$ node node_modules/polymer-bundler/lib/bin/polymer-bundler.js \
  --in-html src/settings.html
  --in-html src/lazy-loaded.html
  --in-html vendor/polymer/v1/polymer.html
  --in-html vendor/polymer/v1/polymer-mini.html
  --in-html vendor/polymer/v1/polymer-micro.html
  --shell settings.html
  --outdir bundled
```

Polymer Bundler can also be used as a library and if your build gets more complicated it might make sense to just build a custom .js file to execute rather than the bin/polymer-bundler.js

**Comment by usergenic** [comment]
I'm going to close this issue because I don't think it makes sense to adjust polymer-bundler's behavior without a deeper design review and it appears the code separation can be addressed by polymer-bundler's multi-bundle/sharded build model.  Re-open if blocked.
