### ISSUE TITLE
De-duping dependencies across polymer-bundler passes

### ISSUE THREAD

**Issue by govis** [Polymer/polymer-bundler#595]
I'm trying to bundle an application in 4 bundles: <code>Shell</code>, <code>Bundle1</code>, <code>Bundle2</code> and <code>Bundle3</code> with Shell containing dependencies shared between Shell.html and Bundle1.html and shared_bundle_1.html containing dependencies shared between Bundle2.html and Bundle3.html less what has already been bundled in Shell.html and Bundle1.html.

The following 2 ommands work independently, but some dependencies get duplicated - is it possible to de-dup them somehow?
<pre><code>polymer-bundler --root rootDir --manifest-out manifest.json --out-dir outDir --shell "shell.html" --in-html "shell.html" --in-html "bundle1.html"

polymer-bundler --root rootDir --manifest-out manifest.json --out-dir outDir --in-html "bundle2.html" --in-html "bundle3.html"</code></pre>

**Comment by justinfagnani** [comment]
The bundle is meant to be run once to produce all the bundles you need. Is there a reason your not configuring multiple fragments?

**Comment by govis** [comment]
Thanks @justinfagnani for your response. It's my goal to try keeping the shell slim. It contains splash screen and only bundles Polymer and some mixins. Bundle 1 is lazy-loaded upon shell initialization and contains most frequently used pages and core set of elements. Bundle 2 & 3 contain other less used pages and can be fat, so would rather not bundle their dependencies into the shell. I need to bundle as I have a lot of custom elements and can't leverage server push in my server environment.

As I understand SPA fragments are individual pages and if I were to bundle them(with their dependencies) individually - I still wouldn't be able to de-dup the dependencies whould I?

**Comment by justinfagnani** [comment]
The Bundler doesn't de-dupe dependencies because it never duplicates them in the first place, which is why it's important to only do one run of the Bundler, configured properly.

Fragments are any dynamically loaded dependencies, they could be pages are anything else loaded with `importHref` or lazy-imports: https://www.polymer-project.org/2.0/docs/tools/polymer-json

If you configure a shell for shell.html, and a fragment for each of the bundle.html files, it should work fine.

**Comment by govis** [comment]
I see, that might actually work for me, so I'll try to setup my bundles as fragments. From reading the docs it appears that it'll generate a single shared dependencies bundle for my bundles 1, 2 & 3, which will get imported along with Bundle 1 when shell loads. 

With other bundles being fat and rarely loaded - do you think it would make sense for a future enhancement to have a fragment spawn a new shared dependencies bundle to make it possible for more then one shared bundle (I imagine previously created bundles would have to be linked as well as the order of import may not be guaranteed)?

On a separate note - is it possible to feed <code>polymer.json</code> to <code>polymer-bundler</code>directly or does it have to be invoked by the <code>polymer build</code>? Thanks.

**Comment by govis** [comment]
I see that bundle groups idea was brought up in #511 and agree that it could get hairy with managing imports order, but something as simple as incremental creation of new shared bundles (as required) along with linking previously created bundles as per build sequence might be a compromise.

**Comment by web-padawan** [comment]
@govis here is the example of how  you can configure bundle merge strategy with `polymer-build`:

```
const polymer = require('polymer-build');
const bundler = require('polymer-bundler');
const polymerJSON = require('./polymer.json');
const project = new polymer.PolymerProject(polymerJSON);

var buildStream = merge(project.sources(), project.dependencies())
    .pipe(project.bundler({
        strategy: bundler.generateShellMergeStrategy(polymerJSON.shell, 4)
   }))
```

This results in the following workflow:
1. If the component is only imported by 3 fragments, it will be placed to separate bundle
2. If the component is imported by 4 fragments or more, and / or shell, it will be placed to shell

Any other tricks, like manual excluding etc, are unreliable, can cause code duplications and runtime errors.

**Comment by govis** [comment]
Thanks @web-padawan for your suggestion. Given your experience with generating optimal bundles I'd like to give it a try - is it possible to run it directly with node? I saved your snippet as <code>my_build_script.js</code> but when I try executing it with node I get <pre><code>Cannot find module 'polymer-build'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (my_build_script.js)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)</code></pre>

My current build is done with running <code>polymer-bundler</code> and <code>polymer build</code> commands and I'm a bit new to the gulp setup.

**Comment by web-padawan** [comment]
@govis you can find an example gulpfile [here](https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/master/generators/app/gulpfile.js). If you are not inclined to use `gulp`, you could just use Vinyl streams since `polymer-build` supports them as well.

**Comment by govis** [comment]
Finally have made some progress. I created <code>polymer.json</code> as follows:
<pre><code>{
  "entrypoint": "index.html",
  "shell": "shell.html",
  "fragments": [
      "bundle1.html",
      "bundle2.html",
      "bundle3.html"
  ],
  "lint": {
    "rules": [ "polymer-2-hybrid" ]
  },
  "builds": [
    { "preset": "es6-bundled" }
  ]
}</code></pre>

For some reason <code>polymer build</code> would not generate any shared bundles - it looks like shared deps get bundled into the shell by default, which is not ideal.

So I created custom <code>gulpfile.js</code> with <code>generateSharedDepsMergeStrategy(3)</code> and executed it with <code>gulp build</code> - now my shell stays slim and I get a few shared bundles created. Unfortunately documentation is fairly dry on how to get it setup from scratch, thanks @web-padawan for the link. Both <code>generateSharedDepsMergeStrategy(3)</code> and <code>generateShellMergeStrategy(project.shell, 3)</code> appear to generate identical output in my case.

**Comment by govis** [comment]
Actually before I close it - could you please explain why <code>polymer build</code> does not generate any shared bundles but <code>generateSharedDepsMergeStrategy</code> and <code>enerateShellMergeStrategy</code>do and if it's possible to feed the bundle strategy/config via <code>polymer.json</code> or some other way?

Having to resort to a custom <code>gulpfile.js</code> also requires dealing with minification and other things already offered by <code>polymer-build</code>.

**Comment by web-padawan** [comment]
@govis see my comment [here](https://github.com/Polymer/polymer-bundler/issues/598#issuecomment-318007119) for some clarification.

Regarding your question about how to keep the shell slim: this depends on how much fragments import your heavy dependencies. In our project we defer loading some app-level stuff, e. g. [i18n library](https://github.com/twitter/twitter-cldr-js), withe the help of [polymer-lib-loader](https://github.com/LasaleFamine/polymer-lib-loader) element.

This enables us to reduce shell size and to use better caching, since libraries like this are not expected to change really often. As a drawback, we have to ensure `i18n` is available before doing some date, time or currency formatting.

The number passed to `generateShellMergeStrategy` as a `maybeMinEntrypoints` parameter iiss up to you. We configured it to `4` and now we have 49 shared bundles, while also having 65 fragments, and our shell os still big (174 Kb gzipped) due to `moment` library which is imported from 6 fragments.

I'd also have to say that, the more you increase this humber, the lesser shell becomes (and thus first paint faster), but this also means more requests later on, e. g. our pages can import from 6 to 10 shared bundles each. This makes situation closer to an unbundled approach.

**Comment by govis** [comment]
Thanks @web-padawan I am afraid those issues will keep coming until there's more info around bundling strategies et cetera. I agree with @vdegenne that it seems strange when those tools produce different output even though one uses the other. From poking at the code it looks like <code>polymer-build</code> uses <code>generateShellMergeStrategy</code> when shell is provided and <code>polymer-bundler</code> falls back to <code>generateSharedDepsMergeStrategy</code> by default.

I still don't get why shell should get any dependencies from lazy-loaded fragments bundled into it or linked via any shared deps bundles - it doesn't need them and it will only slow it down at startup. Polymer [doc ](https://www.polymer-project.org/1.0/toolbox/server) for PRPL pattern states that "The shell is responsible for dynamically importing the fragments as needed" and the diagram shows no linkages between the shell and shared dependencies.

**Comment by govis** [comment]
Here's the same [diagram](https://www.polymer-project.org/2.0/toolbox/prpl) for Polymer 2.0

**Comment by vdegenne** [comment]
@govis not sure if that will be of any use for you but I spent few days trying to understand `polymer-build` behaviors and tools behind because I really needed to find a way to output only one minimized file giving a shell as the input, and I made a concatenation of tools inside a yarn package with an example case you can find on this git page, hope it will help : [https://github.com/vdegenne/polymer-micro-build-toolbox](https://github.com/vdegenne/polymer-micro-build-toolbox)

**Comment by govis** [comment]
Thanks @vdegenne for sharing this - I'll have a look. I've spent quite a bit of time as well trying to come up with an optimal packaging approach. We ended up converting to ES6 modules syntax. This allows for bundling with rollup and/or webpack. There's also [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader) plugin for Webpack that converts <code>dom-module</code> markup to ES6 module as well, so that it can be bundled together with the underlying javascript of the app itself - I think this is going to be direction moving forward. More info in Rob Dodson article [here](http://robdodson.me/how-to-use-polymer-with-webpack)
